[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./out"}, {access = "read", path = "./test/bin"}, {access = "read", path = "./test"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
